Practical 4

Create a forward and backward difference table

1.

In [3]:
import numpy as np
import pandas as pd

In [5]:
x=[0,1,2,3,4]
y=[0,1,4,9,16]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=diff_table[i+1][j-1]-diff_table[i][j-1]
df=pd.DataFrame(diff_table,columns=[f"d^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

   x     y  d^1  d^2  d^3  d^4
0  0   0.0  1.0  2.0  0.0  0.0
1  1   1.0  3.0  2.0  0.0  0.0
2  2   4.0  5.0  2.0  0.0  0.0
3  3   9.0  7.0  0.0  0.0  0.0
4  4  16.0  0.0  0.0  0.0  0.0

In [9]:
x=[10,20,30,40,50]
y=[45,65,80,92,100]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=diff_table[i+1][j-1]-diff_table[i][j-1]
df=pd.DataFrame(diff_table,columns=[f"d^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

    x      y   d^1  d^2  d^3  d^4
0  10   45.0  20.0 -5.0  2.0 -3.0
1  20   65.0  15.0 -3.0 -1.0  0.0
2  30   80.0  12.0 -4.0  0.0  0.0
3  40   92.0   8.0  0.0  0.0  0.0
4  50  100.0   0.0  0.0  0.0  0.0

In [7]:
x=[-1,0,1,2,3,4,5]
y=[-13,-7,-1,11,35,77,143]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=diff_table[i+1][j-1]-diff_table[i][j-1]
df=pd.DataFrame(diff_table,columns=[f"d^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

   x      y   d^1   d^2  d^3  d^4  d^5  d^6
0 -1  -13.0   6.0   0.0  6.0  0.0  0.0  0.0
1  0   -7.0   6.0   6.0  6.0  0.0  0.0  0.0
2  1   -1.0  12.0  12.0  6.0  0.0  0.0  0.0
3  2   11.0  24.0  18.0  6.0  0.0  0.0  0.0
4  3   35.0  42.0  24.0  0.0  0.0  0.0  0.0
5  4   77.0  66.0   0.0  0.0  0.0  0.0  0.0
6  5  143.0   0.0   0.0  0.0  0.0  0.0  0.0

In [16]:
x=[0,1,2,3,4,5]
y=[-7,-3,6,25,62,129]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=diff_table[i+1][j-1]-diff_table[i][j-1]
df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

<>:9: SyntaxWarning: invalid escape sequence '\D'
<>:9: SyntaxWarning: invalid escape sequence '\D'
C:\Users\student\AppData\Local\Temp\ipykernel_8972\4127606042.py:9: SyntaxWarning: invalid escape sequence '\D'
  df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])

   x      y  $\Delta$^1  $\Delta$^2  $\Delta$^3  $\Delta$^4  $\Delta$^5
0  0   -7.0         4.0         5.0         5.0         3.0         1.0
1  1   -3.0         9.0        10.0         8.0         4.0         0.0
2  2    6.0        19.0        18.0        12.0         0.0         0.0
3  3   25.0        37.0        30.0         0.0         0.0         0.0
4  4   62.0        67.0         0.0         0.0         0.0         0.0
5  5  129.0         0.0         0.0         0.0         0.0         0.0

backward>

In [15]:
x=[-1,0,1,2,3,4,5]
y=[-13,-7,-1,11,35,77,143]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-1,j-1,-1):
        diff_table[i][j]=diff_table[i][j-1]-diff_table[i-1][j-1]
df=pd.DataFrame(diff_table,columns=[f"$\nabla$^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

,x,y,$\nabla$^1,$\nabla$^2,$\nabla$^3,$\nabla$^4,$\nabla$^5,$\nabla$^6
0,-1,-13.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,-7.0,6.0,0.0,0.0,0.0,0.0,0.0
2,1,-1.0,6.0,0.0,0.0,0.0,0.0,0.0
3,2,11.0,12.0,6.0,6.0,0.0,0.0,0.0
4,3,35.0,24.0,12.0,6.0,0.0,0.0,0.0
5,4,77.0,42.0,18.0,6.0,0.0,0.0,0.0
6,5,143.0,66.0,24.0,6.0,0.0,0.0,0.0

In [17]:
x=[10,20,30,40,50]
y=[45,65,80,92,100]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-1,j-1,-1):
        diff_table[i][j]=diff_table[i][j-1]-diff_table[i-1][j-1]
df=pd.DataFrame(diff_table,columns=[f"$\nabla$^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

    x      y  $\nabla$^1  $\nabla$^2  $\nabla$^3  $\nabla$^4
0  10   45.0         0.0         0.0         0.0         0.0
1  20   65.0        20.0         0.0         0.0         0.0
2  30   80.0        15.0        -5.0         0.0         0.0
3  40   92.0        12.0        -3.0         2.0         0.0
4  50  100.0         8.0        -4.0        -1.0        -3.0