Practical 5

Using python create newton divided difference table

In [1]:
import numpy as np
import pandas as pd

In [5]:
x=[2,4,9,10]
y=[4,56,711,980]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=(diff_table[i+1][j-1]-diff_table[i][j-1])/(x[i+j]-x[i])
df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

<>:9: SyntaxWarning: invalid escape sequence '\D'
<>:9: SyntaxWarning: invalid escape sequence '\D'
C:\Users\student\AppData\Local\Temp\ipykernel_9160\824184110.py:9: SyntaxWarning: invalid escape sequence '\D'
  df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])

    x      y  $\Delta$^1  $\Delta$^2  $\Delta$^3
0   2    4.0        26.0        15.0         1.0
1   4   56.0       131.0        23.0         0.0
2   9  711.0       269.0         0.0         0.0
3  10  980.0         0.0         0.0         0.0

In [6]:
x=[2,4,19,10]
y=[4,56,111,980]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=(diff_table[i+1][j-1]-diff_table[i][j-1])/(x[i+j]-x[i])
df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

<>:9: SyntaxWarning: invalid escape sequence '\D'
<>:9: SyntaxWarning: invalid escape sequence '\D'
C:\Users\student\AppData\Local\Temp\ipykernel_9160\3607398075.py:9: SyntaxWarning: invalid escape sequence '\D'
  df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])

    x      y  $\Delta$^1  $\Delta$^2  $\Delta$^3
0   2    4.0       26.00       -1.31       -1.92
1   4   56.0        3.67      -16.70        0.00
2  19  111.0      -96.56        0.00        0.00
3  10  980.0        0.00        0.00        0.00

In [7]:
x=[3,4,29,30]
y=[4,56,711,780]
n=len(x)
diff_table=np.zeros((n,n))
diff_table[:,0]=y
for j in range(1,n):
    for i in range(n-j):
        diff_table[i][j]=(diff_table[i+1][j-1]-diff_table[i][j-1])/(x[i+j]-x[i])
df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])
df.insert(0,'x',x)
df.round(2)

<>:9: SyntaxWarning: invalid escape sequence '\D'
<>:9: SyntaxWarning: invalid escape sequence '\D'
C:\Users\student\AppData\Local\Temp\ipykernel_9160\3879536819.py:9: SyntaxWarning: invalid escape sequence '\D'
  df=pd.DataFrame(diff_table,columns=[f"$\Delta$^{i}" if i>0 else 'y' for i in range(n)])

    x      y  $\Delta$^1  $\Delta$^2  $\Delta$^3
0   3    4.0        52.0       -0.99         0.1
1   4   56.0        26.2        1.65         0.0
2  29  711.0        69.0        0.00         0.0
3  30  780.0         0.0        0.00         0.0